### ISSUE TITLE
Calendar Add-on: No such file or directory: '/config/dwains-dashboard/views/partials/heading.yaml'

### ISSUE THREAD

**Issue by dm7500** [dwainscheeren/dwains-dashboard-addons#142]
Receiving the below error when adding the Calendar add-on to House Info.

![image](https://user-images.githubusercontent.com/5718250/148814169-2c890099-c728-42d8-9d99-f97e97d3d6f2.png)

My House Info script is below:

```yaml
house_information:
  favorites:
    - entity: input_boolean.occupied_mode
    - entity: input_boolean.night_mode
    - entity: input_boolean.guest_mode
    - entity: input_boolean.party_mode
    - entity: input_boolean.vacation_mode

  addons:
    - name: Calendar
      icon: mdi:calendar
      path: 'dwains-dashboard/addons/house_information/calendar/page.yaml'
      data:
        calendars:
          - calendar.rocket_launches
          - calendar.birthdays
          - calendar.garbage_collection
```

My page.yaml for Calendar is below, located at `config\dwains-dashboard\addons\house_information\calendar`

```yaml
- !include
  - ../../../views/partials/heading.yaml
  - title: {{ name }}
- type: custom:atomic-calendar-revive
  style: |
    ha-card {
      border-radius: 5px;
      background-color: var(--dwains-theme-primary);
    }
    .cal-titleContainer {
      display: none;
    }
  showProgressBar: false
  eventBarColor: 'var(--dwains-theme-grey)'
  dayWrapperLineColor: 'var(--dwains-theme-grey)'
  timeColor: 'var(--dwains-theme-grey)'
  entities:
    {{ (data | fromjson)['calendars'] }}
```

Atomic Calendar is installed via HACS
