### ISSUE TITLE
Convert Sonos to a More Page

### ISSUE THREAD

**Issue by Flight777** [dwainscheeren/dwains-dashboard-addons#65]
I'm having trouble to still deduct the construct of the page.yaml of the different add-ons (there seems to be very limited documentation so far).

Could anyone give me some guidance how I would be able to convert the excellent Sonos add-on for Rooms, to a More Page add-on? I'd like to have on central page to control all Sonos devices in the house :)

Very eager to lear how to do it myself in the future, so any links to good documentation will help greatly.

Thanks for the outstanding job on the interface!!

**Comment by Klumpke** [comment]
You can do the following to get it as a More page.

- Copy this [page.yaml](https://github.com/dwainscheeren/dwains-dashboard-addons/blob/master/rooms/sonos/page.yaml) to your `<config dir>/dwains-dashboard/addons/more_page/sonos` directory.
- Add the code below to your `more_page.yaml` file in `<config dir>/dwains-dashboard/configs`.
- Change the entities and buttons to the one you are using in your HA configuration.

```yaml
      - name: Sonos
        icon: mdi:speaker
        path: 'dwains-dashboard/addons/more_page/sonos/page.yaml'
        data:
          platform: sonos
          speakers:
            - entity: media_player.sonos_livingroom
              name: Living Room
            - entity: media_player.sonos_kitchen
              name: Kitchen
            - entity: media_player.sonos_diningroom
              name: Diningroom
            - entity: media_player.sonos_garden
              name: Garden
          buttons:
            - name: Radio 538
              type: source
              id: Radio 538
            - name: 100% NL
              type: source
              id: 100% NL
            - name: Qmusic
              type: source
              id: Qmusic
            - name: TV
              icon: mdi:television
              type: source
              id: TV
```
