### ISSUE TITLE
Printer AddOn - yaml error

### ISSUE THREAD

**Issue by GoTTi74** [dwainscheeren/dwains-dashboard-addons#67]
While in "File editor" I'm getting the following syntax error:
 missed comma between flow collection entries at line 16, column 29:
            {{ (data | fromjson)['printer'] }}
                                ^
and the printer add on doesn't load for the room configured in rooms.yaml

Any idea why I'm getting this?

**Comment by GoTTi74** [comment]
strange... the past few days I could reload the dashboard calling the dwains_dashboard.reload service. Currently this doesn't seem to work (for me) and I have to restart HA. 

Seems that I can ignore the syntax error and the printer add on loaded after restarting HA only.

Same happens if I change a room name in rooms.yaml. The new name only shows in the dashboard after HA restart not after calling "dwains_dashboard.reload"

**Comment by Klumpke** [comment]
Could you share your `rooms.yaml` code of the addon part?

**Comment by GoTTi74** [comment]
Hi @Klumpke 

Thank you for your support. It seems that my Dashboard doesn't reload properly after calling the "dwains_dashboard.reload" service. After I restarted HA, the Printer Add On is working now...

Anyway, this is the add on part in the rooms.yaml
```
    addons:
      - name: Printer
        icon: mdi:printer
        path: 'dwains-dashboard/addons/rooms/office/printer/page.yaml'
        button_path: 'dwains-dashboard/addons/rooms/office/printer/button.yaml'
        data:
          printer:
            - entity: sensor.hp_printer_status
              name: State
            - entity: sensor.hp_printer_printer
              name: Total printed pages
            - entity: sensor.hp_printer_scanner
              name: Total scanned pages
          cardridges:
            - entity: sensor.hp_printer_toner_black
              name: Black
              color: Black
            - entity: sensor.hp_printer_toner_cyan
              name: Cyan
              color: MediumTurquoise
            - entity: sensor.hp_printer_toner_magenta
              name: Magenta
              color: Magenta
            - entity: sensor.hp_printer_toner_yellow
              name: Yellow
              color: Gold
```
Still having the syntax error in the HA File editor but I guess it doesn't matter as it doesn't seem to affect the add on.
